package config

const (
	BATCH_SIZE_DATABASE     = 1_000
	BATCH_SIZE_CACHE        = 1_000
	STREAM_QUEUE_SIZE       = 3
	CACHE_TARGET_INDEX_SIZE = 10_000
	CACHE_MIN_INDEXES       = 5
	CACHE_LEARNING_RATE     = 0.1
)
